### ISSUE TITLE
HU02: Consultar la información detallada de un álbum.

### ISSUE THREAD

**Issue by bitnavigator** [areyna04/ClaseAppMovil#2]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.

**Comment by bitnavigator** [comment]
| Tarea| Estimación Horas | Responsable | Estado | Avance |
|--------|--------|--------| --------|--|
| Crear Modelo en Backend de detalle de album. | 2 |@bitnavigator      | Pendiente    | |
| Crear interfaz para mostrar el detalle de un album. | 3 | @Waponteg | Pendiente    | |
| Crear pruebas unitarias para el backend. | 3 |@lwilches | Pendiente    | |
| Realizar pruebas funcionales. | 2 |    @areyna04      | Pendiente    | |
| Realizar despliegue, release y generación de APK. | 3 | @areyna04      | Pendiente    | |
| Actualizar documentación - Modelos. | 3 |@Waponteg | Pendiente    | |

**Comment by areyna04** [comment]
**Criterios de Aceptación**

| Item | Criterio |
|--|--|
| 1 | *En la interfaz de app movil de listado de álbumes, se debe tener un boton para acceder al detalle. |
| 2 | *En la interfaz de app movil de detalle de album, se debe poder ver el nombre de album, tracks y artista |
