### ISSUE TITLE
HU04: Consultar la información detallada de un artista.

### ISSUE THREAD

**Issue by bitnavigator** [areyna04/ClaseAppMovil#4]
Como usuario visitante quiero ver el detalle de un artista para ampliar la información sobre él.

**Comment by Waponteg** [comment]
| Tarea| Estimación h | Responsable | Estado | Avance |
|--------|--------|--------| --------|--|
| Crear Modelo en Backend -kotlin| 1| @lwilches    | Pendiente    | |
| Agregar endpoint para traer información de un artista| 2 | @lwilches    | Pendiente | |
| Crear interfaz en el frontEnd para mostrar la información| 4 | @lwilches    |    Pendiente   | |
| Crear pruebas unitarias para el backend | 3 | @areyna04    | Pendiente    | |
| Realizar pruebas funcionales | 2 | @Waponteg |   Pendiente | |
| Realizar despliegue y generación de APK | 3 | @bitnavigator   |   Pendiente | |
| Actualizar documentación - Modelos. | 3 | @areyna04  |   Pendiente | |
