### ISSUE TITLE
HU09: Comentar un álbum.

### ISSUE THREAD

**Issue by bitnavigator** [areyna04/ClaseAppMovil#8]
Como coleccionista quiero comentar un álbum para dar a conocer mi opinión.

**Comment by bitnavigator** [comment]
| Tarea| Estimación Horas | Responsable | Estado | Avance |
|--------|--------|--------| --------|--|
| Actualizar servicio de album para incluir comentarios. | 1 | @lwilches | Pendiente    | |
| Crear interfaz para mostrar los comentarios de un album. | 4 |  @areyna04      | Pendiente    | |
| Crear pruebas unitarias para el backend. | 3 | @bitnavigator | Pendiente    | |
| Realizar pruebas funcionales. | 2 |    @Waponteg | Pendiente    | |
| Realizar despliegue, release y generación de APK. | 3 |  @bitnavigator | Pendiente    | |
| Actualizar documentación - Modelos. | 3 | @areyna04      | Pendiente    | |

**Comment by areyna04** [comment]
** Criterios de Aceptación**

| Item | Criterio |
|--|--|
| 1 | *En la interfaz de usuario de detalle de album deben aparecer los comentarios y un botón para nuevos comentarios. |
